export const carCompanies = [
  {
    label: "Select Company",
    value: "",
  },
  { label: "Alfa Romeo", value: "Alfa Romeo" },
  { label: "Bentley", value: "Bentley" },
  { label: "BMW", value: "BMW" },
  { label: "Buick", value: "Buick" },
  { label: "Cadillac", value: "Cadillac" },
  { label: "Chevrolet", value: "Chevrolet" },
  { label: "Chrysler", value: "Chrysler" },
  { label: "Dodge", value: "Dodge" },
  { label: "Ferrari", value: "Ferrari" },
  { label: "FIAT", value: "FIAT" },
  { label: "Ford", value: "Ford" },
  { label: "Freightliner", value: "Freightliner" },
  { label: "Genesis", value: "Genesis" },
  { label: "GMC", value: "GMC" },
  { label: "Honda", value: "Honda" },
  { label: "Hyundai", value: "Hyundai" },
  { label: "INFINITI", value: "INFINITI" },
  { label: "Jaguar", value: "Jaguar" },
  { label: "Jeep", value: "Jeep" },
  { label: "Kia", value: "Kia" },
  { label: "Lamborghini", value: "Lamborghini" },
  { label: "Land Rover", value: "Land Rover" },
  { label: "Lexus", value: "Lexus" },
  { label: "Lincoln", value: "Lincoln" },
  { label: "Maserati", value: "Maserati" },
  { label: "MAZDA", value: "MAZDA" },
  { label: "McLaren", value: "McLaren" },
  { label: "Mercedes-Benz", value: "Mercedes-Benz" },
  { label: "MINI", value: "MINI" },
  { label: "Mitsubishi", value: "Mitsubishi" },
  { label: "Nissan", value: "Nissan" },
  { label: "Porsche", value: "Porsche" },
  { label: "Ram", value: "Ram" },
  { label: "Rolls-Royce", value: "Rolls-Royce" },
  { label: "Smart", value: "Smart" },
  { label: "Subaru", value: "Subaru" },
  { label: "Tesla", value: "Tesla" },
  { label: "Toyota", value: "Toyota" },
  { label: "Volkswagen", value: "Volkswagen" },
  { label: "Volvo", value: "Volvo" },
];
