import {
  BsBank2,
  BsFileRuledFill,
  BsFillHouseAddFill,
  BsFillHousesFill,
} from "react-icons/bs";
import {
  FaBuilding,
  FaCar,
  FaCheckCircle,
  FaEdit,
  FaFileAlt,
  FaGlobe,
  FaHeart,
  FaLinkedin,
  FaMinus,
  FaMoon,
  FaPhone,
  FaPlus,
  FaPrint,
  FaRegCopy,
  FaRegHeart,
  FaRegTrashAlt,
  FaStar,
  FaSun,
  FaUniversity,
  FaUpload,
} from "react-icons/fa";
import {
  FaCarTunnel,
  FaClone,
  FaFileInvoice,
  FaMoneyCheck,
  FaMoneyCheckDollar,
  FaPeopleRoof,
  FaRegFilePdf,
  FaSheetPlastic,
} from "react-icons/fa6";
import {
  GrAnnounce,
  GrHostMaintenance,
  GrSchedules,
  GrUserManager,
  GrVmMaintenance,
} from "react-icons/gr";
import {
  IoIosArrowDown,
  IoIosBed,
  IoIosPaper,
  IoIosPeople,
  IoMdHome,
  IoMdMail,
} from "react-icons/io";
import {
  IoCardOutline,
  IoCarSharp,
  IoCloseSharp,
  IoLocationSharp,
  IoLogoFacebook,
  IoLogoInstagram,
  IoLogoTiktok,
  IoLogoTwitter,
} from "react-icons/io5";
import { LuFolderCog, LuUpload } from "react-icons/lu";
import {
  MdAccountCircle,
  MdAttachMoney,
  MdCurrencyExchange,
  MdDashboard,
  MdEmail,
  MdOutlineClose,
  MdOutlineDone,
  MdOutlinePayment,
  MdOutlinePets,
  MdPermMedia,
} from "react-icons/md";
import { PiBuildingApartmentFill } from "react-icons/pi";
import { RiBillFill, RiDiscountPercentFill } from "react-icons/ri";
import { SlCalender } from "react-icons/sl";
import { TbCashRegister, TbLogout2 } from "react-icons/tb";

export const Icons = {
  Location: IoLocationSharp,
  Building: FaBuilding,
  Heart: FaHeart,
  FilledHeart: FaRegHeart,
  Upload: FaUpload,
  Facebook: IoLogoFacebook,
  Instagram: IoLogoInstagram,
  Twitter: IoLogoTwitter,
  Tiktok: IoLogoTiktok,
  Close: IoCloseSharp,
  Calender: SlCalender,
  Edit: FaEdit,
  Delete: FaRegTrashAlt,
  Print: FaPrint,
  Plus: FaPlus,
  Minus: FaMinus,
  Copy: FaRegCopy,
  Tik: MdOutlineDone,
  DownArrow: IoIosArrowDown,
  Star: FaStar,
  Bed: IoIosBed,
  Linkedin: FaLinkedin,
  Check: FaCheckCircle,
  dashboard: MdDashboard,
  application: FaFileAlt,
  resident: FaPeopleRoof,
  properties: BsFillHouseAddFill,
  apartment: PiBuildingApartmentFill,
  propertiesList: BsFillHousesFill,
  propertyRules: BsFileRuledFill,
  work: GrHostMaintenance,
  tour: GrSchedules,
  employee: IoIosPeople,
  invoice: FaFileInvoice,
  paymentSetting: MdOutlinePayment,
  subscription: MdAttachMoney,
  account: MdAccountCircle,
  asset: MdPermMedia,
  logout: TbLogout2,
  pets: MdOutlinePets,
  cars: IoCarSharp,
  docs: IoIosPaper,
  check: FaMoneyCheck,
  utility: RiBillFill,
  mail: IoMdMail,
  closeBtn: MdOutlineClose,
  Clone: FaClone,
  House: IoMdHome,
  Car: FaCar,
  Announce: GrAnnounce,
  Parking: FaCarTunnel,
  Sun: FaSun,
  Moon: FaMoon,
  Bank: BsBank2,
  Card: IoCardOutline,
  Email: MdEmail,
  Phone: FaPhone,
  Website: FaGlobe,
  Offer: RiDiscountPercentFill,
  Money: MdCurrencyExchange,
  UploadV2: LuUpload,
  Folder: LuFolderCog,
  PDF: FaRegFilePdf,
  Statement: FaMoneyCheckDollar,
  Deposit: TbCashRegister,
  Sheet: FaSheetPlastic,
  Provide: GrVmMaintenance,
  University: FaUniversity,
  Manager: GrUserManager,
};
